# Generated by Django 4.2.2 on 2024-04-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
