# Generated by Django 4.2.2 on 2024-04-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('coach', 'Coach'), ('client', 'Client')], max_length=7),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
